server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  # ── Inventory Service logs ──────────────────────────────────
  - job_name: inventory-service
    static_configs:
      - targets: [localhost]
        labels:
          service: inventory-service
          env: local
          __path__: /logs/inventory/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            endpoint: endpoint
            httpStatus: httpStatus
            latencyMs: latencyMs
      - labels:
          level:
          endpoint:

  # ── Order Service logs ──────────────────────────────────────
  - job_name: order-service
    static_configs:
      - targets: [localhost]
        labels:
          service: order-service
          env: local
          __path__: /logs/order/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            endpoint: endpoint
            httpStatus: httpStatus
            latencyMs: latencyMs
      - labels:
          level:
          endpoint:

  # ── Shipping Service logs ───────────────────────────────────
  - job_name: shipping-service
    static_configs:
      - targets: [localhost]
        labels:
          service: shipping-service
          env: local
          __path__: /logs/shipping/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            endpoint: endpoint
            httpStatus: httpStatus
            latencyMs: latencyMs
      - labels:
          level:
          endpoint:
