server:
  port: 8080

spring:
  application:
    name: order-service

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,OPTIONS"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
  health:
    status:
      http-mapping:
        DOWN: 200
  metrics:
    tags:
      service: order-service
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.incidentlab: DEBUG
