server:
  port: 8081

spring:
  application:
    name: inventory-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,OPTIONS"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      service: inventory-service
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.incidentlab: DEBUG
